name = "line-bot-cf-worker-sample"
main = "src/index.ts"
compatibility_date = "2022-11-23"

[[ d1_databases ]]
binding = "DB" # i.e. available in your Worker on env.DB
database_name = "open-ai-db"
database_id = "410ec73d-6f99-4536-ba5f-cd9e01dd6224"